services:
  egs-scraper-app:
    image: marcus1939/egs-scraper-app:latest
    volumes:
      - ./games_info.json:/app/games_info.json
    working_dir: /app
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
